#!bin/sh
. "$(dirname "$0")/_/husky.sh"

echo ' Styling, testing and building your project before committing'

# Check Prettier
npm run check-format || 
(
  echo 'Prettier check failed. Run npm run format, add changes and try commit again.'
  false;
)

# Check ESLint
npm run check-lint ||
(
  echo 'ESLint check failed. Make the required changes listed above, add changes and try to commit again.'
  false; 
)

# Check tsconfig standards
npm run check-types ||
(
  echo 'TypeScript check failed. Make the required changes listed above, add changes and try to commit again.'
  false;
)

# Build
npm run build ||
(
  echo "Your build failed, view the errors above"
  false;
)

# If everything passes... Now we can commit
echo '✅✅✅✅ You win this time... I am committing this now. ✅✅✅✅'